### ISSUE TITLE
Request: Add a command to retrieve message body

### ISSUE THREAD

**Issue by itsgaryk** [AnotherCat/message-manager-site#1]
A text file gets generated after doing a !send [channel ID] [message] however it would be useful if a command existed which generates a text file containing the body of the message.

It is useful in the scenario of having a single channel for bot commands (5+ bots) and finding it difficult to scroll up and retrieve the original or edited text file.

For example:
!export [channel ID] [message ID]

Generates a text file containing the body of the message.

**Comment by AnotherCat** [comment]
A command `~fetch <channel-id> <message-id>` already exists which should output the message as a `.txt` file.
However it may not be in the help command :facepalm: (something i also need to update)

**Comment by AnotherCat** [comment]
Also if next time you could open requests that are specifically for the bot on the bots repository [AnotherCat/message-bot](https://github.com/anothercat/message-bot) (sorry i might have not been clear enough in the naming and description)
